#:kivy 1.0
<AppLayout>
	GridLayout:
		size: root.width, root.height
		cols: 1
		GridLayout:
			cols: 1

			Label:
				text: "Dictionary"
				font_size: 32

		GridLayout:
			cols: 2

			TextInput:
				id: search_word
				size_hint_y: None
				height: 50

			Button:
				text: "Search"
				size_hint_x: None
				size_hint_y: None
				width: 100
				height: 50
				on_press: root.dictionary_search()

		GridLayout:
			cols: 1

			TextInput:
				id: display
